### ISSUE TITLE
[rnv run Android] unable to run android on M1 mac due to incompatible compileSdk 

### ISSUE THREAD

**Issue by ShawYuForte** [flexn-io/renative#924] opened 2022-10-11 23:40 UTC
**Describe the bug**

cannot run android app.  I tried multiple templates and got this same issue

```
│ [ error ] [run] COMMAND:

./gradlew assembleDebug -x bundleReleaseJsAndAssets

FAILED with ERROR:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.mediarouter:mediarouter:1.3.0.
     AAR metadata file: /Users/shawyu/.gradle/caches/transforms-3/666800093c11ebe5b27abe6efbbdd29c/transformed/mediarouter-1.3.0/META-INF/com/android/build/gradle/aar-metadata.properties.
```

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**To Reproduce**

1. `rnv new`
2. `cd <project_name>`
3. `rnv run -p android'
4. select simulator - Pixel API 31 with Android 12 arm64
5. see the error

**Screenshots or copy&paste**
![image](https://user-images.githubusercontent.com/113205525/195217821-0f75a26e-015a-4cf8-a9fe-33b5c9a7932c.png)
![image](https://user-images.githubusercontent.com/113205525/195217846-172983c9-f449-477a-98ed-c55098978999.png)

**Desktop (please complete the following information):**

-   OS: OSX Monterey 12.2 M1 chip
-   Node Version 16.17.1
-   RNV Version 0.36.1

**Additional context**
If this is not a bug please let me know if I made any mistakes thanks

**Comment by ShawYuForte** [comment] 2022-10-20 19:02
update: 
the working versions I found were:
ReNative: 0.34.0
Android Studio: Chipmunk 2021.2.1 Patch 1
emulator API: 29
template: hello world.

The newest versions for ReNative, Android Studio, templates, etc.. are still having the same issue.  Please advice, thanks

**Comment by umar-muhammad-apl** [comment] 2023-02-27 13:15
Did anyone solved this issue ? I am facing the same issue with following specifications. How can we change SDK mentioned in project files, because if I change it from 30 -> 31. It changes back to 30 automatically. 
OS: OSX Monterey 12.3.1 Intel Chip
Node Version 16.17.0
RNV Version 0.36.1

**Comment by GabrieleKaceviciute** [comment] 2023-07-31 08:55
@ShawYuForte thanks for reporting this issue. I can't reproduce it on version 0.37.1
Please update version and try again

**Comment by pauliusguzas** [comment] 2023-08-08 07:46
@ShawYuForte also make sure you are running terminal in rosetta mode

**Comment by GabrieleKaceviciute** [comment] 2023-09-01 10:18
Closing as issue was resolved, feel free to reopen if needed

**Closed by GabrieleKaceviciute** 2023-09-01 10:18 UTC
Labels: bug
