### ISSUE TITLE
Could not find method testImplementation() 

### ISSUE THREAD

**Issue by grkemtneri** [flexn-io/renative#621] opened 2020-11-26 09:30 UTC
**Describe the bug**
when ı start my project, ı am getting Could not find method testImplementation(). I did look solution from stackoverflow . I changed 'I' To 'İ' but reverted back after building.

**To Reproduce**

1. Run command '`rnv run -p androidwear`'
2. See error

```
Build file 'C:\Users\Gorkem\Desktop\workspace\newapp\platformBuilds\blank_androidwear\app\build.gradle' line: 94

A problem occurred evaluating project ':app'.
> Could not find method testImplementation() for arguments [junit:junit:4.12] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

```

**app\build.gradle**

```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    implementation 'org.webkit:android-jsc:+'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
implementation ('com.facebook.react:react-native:+') {
 exclude group: 'com.android.support' 
 exclude group: 'javax.inject' 
 exclude group: 'com.squareup.okhttp3', module: 'okhttp' 
 exclude group: 'com.squareup.okio' 
 }
    implementation project(':react-native-gesture-handler')
    implementation project(':react-native-reanimated')
    implementation project(':react-native-vector-icons')
    implementation "androidx.appcompat:appcompat:1.1.0"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02"
    debugImplementation files("C:/Users/Gorkem/Desktop/workspace/newapp/node_modules/hermes-engine/android/hermes-debug.aar")
    releaseImplementation files("C:/Users/Gorkem/Desktop/workspace/newapp/node_modules/hermes-engine/android/hermes-release.aar")

}
```

**Desktop (please complete the following information):**

-   OS: [e.g. osx, windows 7, ubuntu 16.04]
Windows 10 TR 
-   Node Version [e.g. v10.16.3]
v14.15.0
-   RNV Version [e.g. 0.25.0]
0.31.3

**Comment by erguncaner** [comment] 2021-01-03 20:35
Hi Görkem, have you found a solution?

**Comment by pavjacko** [comment] 2021-01-04 07:09
@grkemtneri @erguncaner I'll into it. in the meantime you can always override core rnv files in this instance copy:

`./node_modules/@rnv/engine-rn/templates/platforms/android/app/build.gradle`

to you project:

`./appConfigs/base/builds/android/app/build.gradle`

this will allow you to manually update/customize build.gradle if you need to add a fix or change not available via rnv options

**Comment by grkemtneri** [comment] 2021-01-04 08:57
I cant see `./node_modules/@rnv/engine-rn/templates`

**Comment by pauliusguzas** [comment] 2023-05-22 08:08
@grkemtneri  thanks for reporting this issue, is this still reproduced on latest rnv version?

**Comment by sudheerrachuri** [comment] 2023-11-06 06:14
Hi 

* What went wrong:
A problem occurred evaluating root project 'uhm'.
> Could not find method testImplementation() for arguments [org.junit.jupiter:junit-jupiter-api:5.6.2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

facing similar issue . Is the solution found ?

**Comment by GabrieleKaceviciute** [comment] 2024-03-15 11:31
I can't reproduce it on rnv 1.0.0-rc.10; node v18.19.0. Could you try it on this version?

**Comment by GabrieleKaceviciute** [comment] 2024-03-29 12:28
Closing as issue was resolved, feel free to reopen if needed

**Closed** 2024-03-29 12:30 UTC
Labels: bug, pinned, support_chain
