### ISSUE TITLE
Windows - Could not find a required file "index.html" under "public" folder

### ISSUE THREAD

**Issue by aymensmurf** [flexn-io/renative#933] opened 2022-11-04 13:51 UTC
**Describe the bug**
I am trying to the template app on windows but I get a "Could not find a required file." error.

**To Reproduce**

1. npx rnv new
2. select the "@rnv/template-starter" template when asked
3. npx rnv run -p windows

**Expected behavior**
Run the template app as an electron app on windows 10

**Screenshots or copy&paste**
```
Could not find a required file.
  Name: index.html
  Searched in: D:\Aymen\Projects\_tests\rnv\new\platformBuilds\app_windows\public
```

![image](https://user-images.githubusercontent.com/7316432/199988248-43f46e61-219d-40a8-8337-b1395b16095a.png)

**Desktop (please complete the following information):**

-   OS: windows 10
-   Node Version: v16.14.0
-   RNV Version: 0.36.1

**Comment by GabrieleKaceviciute** [comment] 2023-07-31 08:06
@aymensmurf thanks for reporting this issue.
I've tested on
OS: Windows 10 Pro
Node Version: v16.13.1
RNV Version: 0.37.1
and this error occurs:

```┌──────────────────────────────────────────────────────────────────────────────┐
│  RNV  BUNDLER STARTED | 31/07/2023, 08:35:58                                 │
│  $ rnv run -p windows                                                        │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.37.1                                                    │
│  Project Name ($package.name): win                                           │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): windows                                                      │
│  Engine ($.platforms.windows.engine): engine-rn-electron                     │
│  Template: @rnv/template-starter@0.37.1                                      │
│  App Config (-c): app                                                        │
│  Build Scheme (-s): debug                                                    │
│  Supported Platforms: windows                                                │
│  Env Info: win32 | x64 | node v16.13.1                                       │
│  Executed Time: 0h:4m:48s:10ms                                               │
│                                                                              │
│ [ success ] [install] \next\dist\lib\find-pages-dir.js requires override by: \@flexn\plugins\pluginTemplates\next\overrides.json. FIXING...DONE
│ [ warn ] [configure] Your app is missing assets at C:\Users\dev\Desktop\qa\win\appConfigs\base,C:\Users\dev\Desktop\qa\win\appConfigs\app.
│                                                                              │
│  Project location:                                                           │
│  C:\Users\dev\Desktop\qa\win\platformBuilds\app_windows                      │
└──────────────────────────────────────────────────────────────────────────────┘
[ task ] [run] _runWebDevServer[1]
[ task ] [run] parsePlugins[2]
(node:2436) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:2436) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
Starting the development server...

One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.

Compiled successfully!

You can now view win in the browser.

  http://localhost:8092

Note that the development build is not optimized.
To create a production build, use yarn build.

assets by path static/ 2.8 MiB
  asset static/js/bundle.js 2.49 MiB [emitted] (name: main) 1 related asset
  asset static/media/Inter-Light.58a136ec3193fa8a63e5.ttf 303 KiB [emitted] [immutable] [from: appConfigs/base/fonts/Inter-Light.ttf] (auxiliary name: main)
  asset static/media/logo.63d54a55b067ffc3e842.png 12.1 KiB [emitted] [immutable] [from: platformAssets/runtime/logo.png] (auxiliary name: main)
asset index.html 1.7 KiB [emitted]
asset asset-manifest.json 356 bytes [emitted]
363 modules
webpack 5.88.2 compiled successfully in 30732 ms
[ task ] [run] _runElectronSimulator:windows[1]
ERROR in src/app/index.tsx:25:10
TS2786: 'View' cannot be used as a JSX component.
  Its instance type 'View' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("C:/Users/dev/Desktop/qa/win/node_modules/@types/react-native/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
    23 |
    24 |     return (
  > 25 |         <View style={theme.styles.container}>
       |          ^^^^
    26 |             <Image
    27 |                 style={theme.styles.image}
    28 |                 source={ICON_LOGO}

ERROR in src/app/index.tsx:26:14
TS2786: 'Image' cannot be used as a JSX component.
  Its instance type 'Image' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("C:/Users/dev/Desktop/qa/win/node_modules/@types/react-native/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
    24 |     return (
    25 |         <View style={theme.styles.container}>
  > 26 |             <Image
       |              ^^^^^
    27 |                 style={theme.styles.image}
    28 |                 source={ICON_LOGO}
    29 |                 {...testProps('template-starter-home-screen-renative-image')}

ERROR in src/app/index.tsx:31:14
TS2786: 'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("C:/Users/dev/Desktop/qa/win/node_modules/@types/react-native/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
    29 |                 {...testProps('template-starter-home-screen-renative-image')}
    30 |             />
  > 31 |             <Text style={theme.styles.textH2} {...testProps('template-starter-home-screen-welcome-message-text')}>
       |              ^^^^
    32 |                 {CONFIG.welcomeMessage}
    33 |             </Text>
    34 |             <Text style={theme.styles.textH2} {...testProps('template-starter-home-screen-version-number-text')}>

ERROR in src/app/index.tsx:34:14
TS2786: 'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
    32 |                 {CONFIG.welcomeMessage}
    33 |             </Text>
  > 34 |             <Text style={theme.styles.textH2} {...testProps('template-starter-home-screen-version-number-text')}>
       |              ^^^^
    35 |                 v {packageJson.version}
    36 |             </Text>
    37 |             <Text style={theme.styles.textH3}>

ERROR in src/app/index.tsx:37:14
TS2786: 'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
    35 |                 v {packageJson.version}
    36 |             </Text>
  > 37 |             <Text style={theme.styles.textH3}>
       |              ^^^^
    38 |                 {`platform: ${Api.platform}, factor: ${Api.formFactor}, engine: ${Api.engine}`}
    39 |             </Text>
    40 |             <Text style={theme.styles.textH3}>

ERROR in src/app/index.tsx:40:14
TS2786: 'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
    38 |                 {`platform: ${Api.platform}, factor: ${Api.formFactor}, engine: ${Api.engine}`}
    39 |             </Text>
  > 40 |             <Text style={theme.styles.textH3}>
       |              ^^^^
    41 |                 {
    42 |                     //@ts-ignore
    43 |                     `hermes: ${global.HermesInternal === undefined ? 'no' : 'yes'}`

ERROR in src/app/index.tsx:46:14
TS2786: 'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
    44 |                 }
    45 |             </Text>
  > 46 |             <Text style={theme.styles.textH3}>{`pixelRatio: ${pixelRatio}, ${fontScale}`}</Text>
       |              ^^^^
    47 |             <TouchableOpacity
    48 |                 onPress={toggle}
    49 |                 style={theme.styles.button}

ERROR in src/app/index.tsx:47:14
TS2786: 'TouchableOpacity' cannot be used as a JSX component.
  Its instance type 'TouchableOpacity' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("C:/Users/dev/Desktop/qa/win/node_modules/@types/react-native/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
    45 |             </Text>
    46 |             <Text style={theme.styles.textH3}>{`pixelRatio: ${pixelRatio}, ${fontScale}`}</Text>
  > 47 |             <TouchableOpacity
       |              ^^^^^^^^^^^^^^^^
    48 |                 onPress={toggle}
    49 |                 style={theme.styles.button}
    50 |                 {...testProps('template-starter-home-screen-try-my-button')}

ERROR in src/app/index.tsx:52:18
TS2786: 'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
    50 |                 {...testProps('template-starter-home-screen-try-my-button')}
    51 |             >
  > 52 |                 <Text style={theme.styles.buttonText}>Try me!</Text>
       |                  ^^^^
    53 |             </TouchableOpacity>
    54 |         </View>
    55 |     );

ERROR in src/config.tsx:6:23
TS2307: Cannot find module '../platformAssets/runtime/logo.png' or its corresponding type declarations.
    4 | import CONFIG from '../platformAssets/renative.runtime.json';
    5 | import '../platformAssets/runtime/fontManager';
  > 6 | import ICON_LOGO from '../platformAssets/runtime/logo.png';
      |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    7 |
    8 | export function testProps(testId: string | undefined) {
    9 |     if (!testId) {

ERROR in src/entry/index.lng.ts:1:24
TS2307: Cannot find module '@lightningjs/sdk' or its corresponding type declarations.
  > 1 | import { Launch } from '@lightningjs/sdk';
      |                        ^^^^^^^^^^^^^^^^^^
    2 | import App from '../app';
    3 |
    4 | const Main = (...args) => Launch(App, ...args);

ERROR in src/pages/404.tsx:7:10
TS2786: 'View' cannot be used as a JSX component.
  Its instance type 'View' is not a valid JSX element.
     5 | export default function Page() {
     6 |     return (
  >  7 |         <View style={themeStyles.container}>
       |          ^^^^
     8 |             <Text style={themeStyles.textH2}>This is custom 404!</Text>
     9 |         </View>
    10 |     );

ERROR in src/pages/404.tsx:8:14
TS2786: 'Text' cannot be used as a JSX component.
  Its instance type 'Text' is not a valid JSX element.
     6 |     return (
     7 |         <View style={themeStyles.container}>
  >  8 |             <Text style={themeStyles.textH2}>This is custom 404!</Text>
       |              ^^^^
     9 |         </View>
    10 |     );
    11 | }

**Comment by GabrieleKaceviciute** [comment] 2024-03-15 11:48
@aymensmurf I can't reproduce it on rnv 1.0.0-rc.10; node v18.19.0. Could you try it on this version?

**Comment by GabrieleKaceviciute** [comment] 2024-03-29 12:32
Closing as issue was resolved, feel free to reopen if needed

**Closed by GabrieleKaceviciute** 2024-03-29 12:32 UTC
Labels: bug
