### ISSUE TITLE
[ error ] Cannot find module 'metro-cache' , when run rnv run -p androidtv

### ISSUE THREAD

**Issue by avishka-codimite** [flexn-io/renative#903] opened 2022-08-19 05:49 UTC
**Describe the bug**
I'm using the ReNative to build a TV app (androidtv, firetv, webtv, tvos, webos, firefoxtv). But I faced an issue when running the app. first I try to start the app using the command  `rnv run -p androidtv`. It will give this kind of error   `[ error ] Cannot find module 'metro-cache'`

**To Reproduce**
1. Run the` rnv new` to create a new project and complete the necessary steps.
2. Select the temple` @rnv/template-starter`
3. Select the version `0.36.2-canary.3 (HEAD: canary)`
4. Select the desired platforms (androidtv, firetv, webtv, tvos, webos, firefoxtv)
5. Run  `rnv run -p androidtv`
6. See module error

**Expected behavior**

> [ error ] Cannot find module 'metro-cache'

**Screenshots or copy&paste**

<img width="1234" alt="Screenshot 2022-08-19 at 10 12 45 AM" src="https://user-images.githubusercontent.com/111336101/185551030-0fd95cd8-5019-446d-8aba-c6a7dba56621.png">

<img width="1234" alt="Screenshot 2022-08-19 at 10 14 47 AM" src="https://user-images.githubusercontent.com/111336101/185551183-fb0a5d26-16bb-4f7c-b3f1-d3dbacc39421.png">

<img width="931" alt="Screenshot 2022-08-19 at 10 24 30 AM" src="https://user-images.githubusercontent.com/111336101/185551331-a19de0ef-14db-487b-a6b7-512763e778d1.png">

**Desktop (please complete the following information):**
-   OS: macOS Monterey, Apple M1 chip
-   Node Version: v16.16.0
-   RNV Version: v0.36.1

**Comment by mihaiblaga89** [comment] 2022-08-21 20:49
@avishka-codimite can you please create a new project but instead of selecting the platforms leave them all selected (the default) and press enter?

**Comment by mihaiblaga89** [comment] 2022-08-21 21:08
@avishka-codimite better yet, please try the latest canary, `0.36.2-canary.3`, this should fix the original issue.

**Comment by francis-robert** [comment] 2022-08-23 17:08
@mihaiblaga89 Just tested with `0.36.2-canary.4` and got the same result as OP.

**Comment by georgelanes** [comment] 2023-01-23 17:28
I have the same problem using de last version.
To solve this problema, install metro-cache as dev dependecie. 

`yarn add metro-cache -D`
or
`npm -I metro-cache --save-dev`

**Comment by GabrieleKaceviciute** [comment] 2023-07-20 11:27
@avishka-codimite  I can't reproduce it on version 0.37.1
Please update version and try again

**Comment by GabrieleKaceviciute** [comment] 2023-08-04 10:05
Closing as issue was resolved, fell free to reopen if needed

**Closed by GabrieleKaceviciute** 2023-08-04 10:05 UTC
Labels: bug, in review
