### ISSUE TITLE
Android Gradle: Could not determine the dependencies of task & deprecated features used

### ISSUE THREAD

**Issue by lKinderBueno** [flexn-io/renative#817] opened 2022-02-22 14:47 UTC
**Describe the bug**
I have created a new renative project, but once I type "npx rnv run -p android", it shows me these errors (check the error.txt file)

**Desktop (please complete the following information):**

-   OS: Windows 11 
-   Node Version v16.13.0
-   RNV Version 0.35.3

[error.txt](https://github.com/renative-org/renative/files/8117555/error.txt)

**Comment by kibs** [comment] 2022-04-20 12:12
I have the same issue, just on a Mac

**Comment by GabrieleKaceviciute** [comment] 2023-07-21 10:09
I can't reproduce it on version 0.37.1. Please update version and try again

**Comment by GabrieleKaceviciute** [comment] 2023-08-04 10:07
Closing as issue was resolved, feel free to reopen if needed

**Closed by GabrieleKaceviciute** 2023-08-04 10:07 UTC
Labels: bug, in review
