### ISSUE TITLE
Building RNV Starter template on WebOS TV fails

### ISSUE THREAD

**Issue by hlz** [flexn-io/renative#884] opened 2022-06-28 10:03 UTC
**Describe the bug**
I'm trying to run the RNV starter template on a WebOS TV and the build process fails out of the box. I've setup a default project with `rnv create` and completed all the steps with the default answers and settings. Then when I run `rnv build -p webos` it fails with `ares-package ERR! [Tips]: The specified path does not exist </Users/hlz/Code/apps/rnv-test/platformBuilds/app_webos/index.html>`.

**To Reproduce**

1. Run command `rnv create` and complete steps 
2. Run `rnv build -p webos`
3. See build error

**Expected behavior**
I expect the app to build an a WebOS IPK

**Desktop (please complete the following information):**

-   OS: MacOS 12.4
-   Node Version 16
-   RNV Version 0.36.1

**Comment by GabrieleKaceviciute** [comment] 2023-06-19 13:50
@hlz thanks for reporting this issue. I can't reproduce it on version 0.37.0-canary.13.
Please update version and try again according to this instruction
https://renative.org/docs/overview/installation#create-new-app

**Comment by GabrieleKaceviciute** [comment] 2023-06-20 13:59
Closing as duplicate https://github.com/flexn-io/renative/issues/964

**Closed by GabrieleKaceviciute** 2023-06-20 13:59 UTC
Labels: bug
