### ISSUE TITLE
Error modules when fires  rnv run

### ISSUE THREAD

**Issue by makenshikuro** [flexn-io/renative#896] opened 2022-07-25 13:06 UTC
**Describe the bug**
Error modules for esbuild fsevents for windows 10 platform

**To Reproduce**

- Create new project  rnv new
- Starter template
- default options,  name  myApp, platforms,  web, tizen, webOs (I tried with all too)
- Cd myapp
- rnv run

**Expected behavior**
Generate scaffolding of files for develop app.

**Screenshots or copy&paste**

File: Error Trace.txt  attached

<img width="1115" alt="renative error" src="https://user-images.githubusercontent.com/6000591/180784086-986499b1-d9a4-4cdd-bd2f-a6a6ddb0ef05.png">
<img width="1112" alt="renative error2" src="https://user-images.githubusercontent.com/6000591/180784297-57b8934a-6f3a-48d7-9c3c-0bded0ffe9f9.png">

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Node 16 LTS
-   RNV Version 0.36.1
[error Trace.txt](https://github.com/renative-org/renative/files/9181383/error.Trace.txt)

**Comment by danilowm** [comment] 2022-08-02 14:21
same here

**Comment by robertrpf** [comment] 2022-08-03 15:24
Same

**Comment by GabrieleKaceviciute** [comment] 2023-07-20 14:44
I can't reproduce it on version 0.37.1. Please update version and try again

**Comment by GabrieleKaceviciute** [comment] 2023-08-04 10:02
Closing as issue was resolved, fell free to reopen if needed

**Closed by GabrieleKaceviciute** 2023-08-04 10:02 UTC
Labels: bug
