### ISSUE TITLE
Error: Unknown option '--inline'

### ISSUE THREAD

**Issue by bgity** [flexn-io/renative#846] opened 2022-04-17 11:34 UTC
After running **rnv run -p tizen --hosted** command displaying unknown option inline.

**Comment by bgity** [comment] 2022-04-18 06:27
Project is running successfully on web but when trying to run for tizen platform showing error Unknown option '--inline'

**Comment by kasinskas** [comment] 2022-04-19 08:39
Which rnv version are you running? If it's older than 0.36.0-canary.3, can you try updating? - https://github.com/renative-org/renative/issues/784

**Comment by bgity** [comment] 2022-04-22 08:35
I am trying to run tizen application in browser. I am using **rnv run -p tizen --hosted** command but it showing me below error

<img width="464" alt="image" src="https://user-images.githubusercontent.com/23340102/164650829-8ab31e34-3f23-4870-8a0c-67e11c2e492e.png">

**Comment by mihaiblaga89** [comment] 2022-04-22 18:30
@bgity But what `rnv` version are you using?

**Comment by kasinskas** [comment] 2022-04-22 19:59
I assume it's latest "not pre-release". I think latest canary currently has issues with a fix to be released in 0.36.0-canary.14, so you could wait for that, or try any canary under 12 in the meantime

**Comment by frannceskka** [comment] 2022-04-28 13:33
I have the same problem when running "rnv run -p webos --hosted" with the latest not pre-release packages. When I try with "0.36.0-canary.4" I get this error: 
![image](https://user-images.githubusercontent.com/60920290/165764146-594d6f94-0b02-46d9-9706-8efd83bcde47.png)


  Any solution?

**Comment by GabrieleKaceviciute** [comment] 2023-06-27 12:43
@bgity, @frannceskka Thanks for reporting this issue. I can't reproduce it on version 0.37.0-rc.1. Please update version and try again

**Comment by GabrieleKaceviciute** [comment] 2023-07-20 11:42
@bgity Closing as issue was resolved, fell free to reopen if needed

**Closed by GabrieleKaceviciute** 2023-07-20 11:42 UTC
Labels: needs more info
