### ISSUE TITLE
rnv run -p xxx doesnt work

### ISSUE THREAD

**Issue by merrymaker14** [flexn-io/renative#909] opened 2022-09-05 10:08 UTC
RNV  SUMMARY | 9/5/2022, 1:03:05 PM                                         │
│  $ rnv run -p android                                                        │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.36.1                                                    │
│  Project Name ($package.name): myApp                                         │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): android                                                      │
│  Build Scheme (-s): debug                                                    │
│  Env Info: win32 | x64 | node v16.16.0                                       │
│  Executed Time: 0h:0m:26s:591ms                                              │
│                                                                              │
│ [ warn ] COMMAND: 

npm install 

```
FAILED with ERROR: 

Command failed with exit code 1: npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: myApp@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.5
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"*" from @rnv/engine-rn-windows@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\musha\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\musha\AppData\Local\npm-cache\_logs\2022-09-05T10_02_47_896Z-debug-0.log

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: myApp@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.5
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"*" from @rnv/engine-rn-windows@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\musha\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\musha\AppData\Local\npm-cache\_logs\2022-09-05T10_02_47_896Z-debug-0.log

Error: Command failed with exit code 1: npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: myApp@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.5
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"*" from @rnv/engine-rn-windows@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\musha\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\musha\AppData\Local\npm-cache\_logs\2022-09-05T10_02_47_896Z-debug-0.log
    at makeError (C:\Users\musha\AppData\Roaming\npm\node_modules\rnv\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\musha\AppData\Roaming\npm\node_modules\rnv\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


 Seems like your node_modules is corrupted by other libs. ReNative will try to fix it for you
│ [ error ] COMMAND: 

npm install 

FAILED with ERROR: 

Command failed with exit code 1: npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: myApp@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.5
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"*" from @rnv/engine-rn-windows@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\musha\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\musha\AppData\Local\npm-cache\_logs\2022-09-05T10_03_00_484Z-debug-0.log

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: myApp@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.5
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"*" from @rnv/engine-rn-windows@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\musha\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\musha\AppData\Local\npm-cache\_logs\2022-09-05T10_03_00_484Z-debug-0.log

Error: Command failed with exit code 1: npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: myApp@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!   node_modules/next
npm ERR!     peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-next
npm ERR!       dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR!   peer react@"^18.2.0" from react-dom@18.2.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@"^17.0.2 || ^18.0.0-0" from next@12.2.5
npm ERR!     node_modules/next
npm ERR!       peer next@">=12.0.8" from @rnv/engine-rn-next@0.36.1
npm ERR!       node_modules/@rnv/engine-rn-next
npm ERR!         dev @rnv/engine-rn-next@"0.36.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@18.0.0
npm ERR! node_modules/react
npm ERR!   peer react@"18.0.0" from react-native@0.69.5
npm ERR!   node_modules/react-native
npm ERR!     peer react-native@"*" from @rnv/engine-rn-windows@0.36.1
npm ERR!     node_modules/@rnv/engine-rn-windows
npm ERR!       dev @rnv/engine-rn-windows@"0.36.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\musha\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\musha\AppData\Local\npm-cache\_logs\2022-09-05T10_03_00_484Z-debug-0.log
    at makeError (C:\Users\musha\AppData\Roaming\npm\node_modules\rnv\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\musha\AppData\Roaming\npm\node_modules\rnv\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by makenshikuro** [comment] 2022-09-05 11:53
Try with    npm install --legacy-peer-deps

**Comment by merrymaker14** [comment] 2022-09-05 14:44
It doesn't help, because when I run `rnv run -p android` it runs `npm install` with the errors.

**Comment by merrymaker14** [comment] 2022-09-05 14:46
That's simple `template-starter`.

**Comment by SmokeSouls** [comment] 2022-09-16 09:44
Has anyone resolved this issue?

**Comment by reytabs** [comment] 2022-10-06 15:35
I have similar issue on this. Is anyone here solve the issue?

**Comment by GabrieleKaceviciute** [comment] 2023-07-28 15:17
I can't reproduce it on version 0.37.1. Please update version and try again

**Comment by pauliusguzas** [comment] 2023-08-08 07:49
Closing as works on windows in 0.37.1

**Closed by pauliusguzas** 2023-08-08 07:49 UTC
Labels: bug, in review
