### ISSUE TITLE
[Linux] rnv new fails on "No project found"

### ISSUE THREAD

**Issue by TheDechev** [flexn-io/renative#973] opened 2023-04-11 07:53 UTC
**Describe the bug**
Cannot use `rnv new` to create a new project, it fails on "No project found" in the newly created directory.

**To Reproduce**

1. Run `rnv new`
2. Use any template

**Expected behavior**
It should create a new project..

**Screenshots**
![image](https://user-images.githubusercontent.com/24282045/231092864-e448594c-7592-42a5-b0a2-13c50f9e0e39.png)

**Desktop**

-   __OS:__ Ubuntu 22.04
-   __Node Version:__ v16.16.0
-   __RNV Version:__ 0.36.1

**Comment by GabrieleKaceviciute** [comment] 2023-06-26 13:52
@TheDechev thanks for reporting this issue, is this still reproduced on latest version?

**Comment by GabrieleKaceviciute** [comment] 2023-07-26 09:26
I can't reproduce it on version 0.37.1 (OS: Ubuntu 22.04.2, Node v18.17.0). Please update version and try again

**Comment by pauliusguzas** [comment] 2023-08-08 06:53
Closing as solved

**Closed by pauliusguzas** 2023-08-08 06:53 UTC
Labels: bug
