### ISSUE TITLE
[Tizen] Focus doesn't work  on real device

### ISSUE THREAD

**Issue by hemko2020** [flexn-io/renative#1497] opened 2024-04-08 14:29 UTC
@pauliusguzas Hello i trying to use remote of my samsung tv but focus doesn't work do you have some solution for resolve this issue? but he work fine on WebOs simulator.

**Comment by GabrieleKaceviciute** [comment] 2024-04-26 08:45
@hemko2020 Thanks for reporting this issue, could you provide rnv and node versions, os type?

**Comment by GabrieleKaceviciute** [comment] 2024-05-15 09:53
Closing as duplicate of https://github.com/flexn-io/renative/issues/127

**Closed by GabrieleKaceviciute** 2024-05-15 09:53 UTC
Labels: bug
